//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsurbideWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_USUARIOS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GEN_USUARIOS()
        {
            this.GEN_CITA = new HashSet<GEN_CITA>();
            this.GEN_JORNADA = new HashSet<GEN_JORNADA>();
            this.GEN_OT = new HashSet<GEN_OT>();
            this.GEN_OT1 = new HashSet<GEN_OT>();
            this.GEN_OT2 = new HashSet<GEN_OT>();
            this.GEN_OT3 = new HashSet<GEN_OT>();
            this.GEN_OTUSUARIO = new HashSet<GEN_OTUSUARIO>();
            this.GEN_OTVEHICULO = new HashSet<GEN_OTVEHICULO>();
            this.GEN_VERSIONES = new HashSet<GEN_VERSIONES>();
            this.GEN_VERSIONES1 = new HashSet<GEN_VERSIONES>();
        }
    
        public int ID { get; set; }
        public string ROWID { get; set; }
        public int IDEMPRESA { get; set; }
        public string ID_INT { get; set; }
        public string CODIGO { get; set; }
        public string LOGIN { get; set; }
        public string PWD { get; set; }
        public string NOMBRE { get; set; }
        public string USERTYPE { get; set; }
        public Nullable<int> AUTO { get; set; }
        public string ACTIVO_SON { get; set; }
        public string APELLIDOS { get; set; }
        public System.DateTime FECHAINSERCION { get; set; }
        public Nullable<System.DateTime> FECHAACTUALIZACION { get; set; }
        public Nullable<int> ITX_TERMINAL { get; set; }
        public Nullable<int> MARCADO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_CITA> GEN_CITA { get; set; }
        public virtual GEN_EMPRESA GEN_EMPRESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_JORNADA> GEN_JORNADA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_OT> GEN_OT { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_OT> GEN_OT1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_OT> GEN_OT2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_OT> GEN_OT3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_OTUSUARIO> GEN_OTUSUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_OTVEHICULO> GEN_OTVEHICULO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_VERSIONES> GEN_VERSIONES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_VERSIONES> GEN_VERSIONES1 { get; set; }
    }
}
