//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsurbideWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_OTUSUARIO
    {
        public int ID { get; set; }
        public int OTID { get; set; }
        public int USUARIOID { get; set; }
        public int IDOTFAMILIA { get; set; }
        public string TIEMPOINI { get; set; }
        public string TIEMPOFIN { get; set; }
        public string TIEMPO { get; set; }
        public string ROWID { get; set; }
        public System.DateTime FECHAINSERCION { get; set; }
        public Nullable<System.DateTime> FECHAACTUALIZACION { get; set; }
        public int BORRADO { get; set; }
        public Nullable<int> ITX_TERMINAL { get; set; }
        public string TIEMPOTXT { get; set; }
    
        public virtual GEN_FAMILIA GEN_FAMILIA { get; set; }
        public virtual GEN_OT GEN_OT { get; set; }
        public virtual GEN_USUARIOS GEN_USUARIOS { get; set; }
    }
}
