//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsurbideWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_OT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GEN_OT()
        {
            this.GEN_CITA = new HashSet<GEN_CITA>();
            this.GEN_CONTACTO = new HashSet<GEN_CONTACTO>();
            this.GEN_EVENTO = new HashSet<GEN_EVENTO>();
            this.GEN_FOTO = new HashSet<GEN_FOTO>();
            this.GEN_OTCONFIRMADA = new HashSet<GEN_OTCONFIRMADA>();
            this.GEN_OTINCIDENCIA = new HashSet<GEN_OTINCIDENCIA>();
            this.GEN_OTMATERIAL = new HashSet<GEN_OTMATERIAL>();
            this.GEN_OTTAREA = new HashSet<GEN_OTTAREA>();
            this.GEN_OTUSUARIO = new HashSet<GEN_OTUSUARIO>();
            this.GEN_OTVEHICULO = new HashSet<GEN_OTVEHICULO>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ESTADOID { get; set; }
        public int IDEMPRESA { get; set; }
        public string CODIGOPARTEID { get; set; }
        public string ID_INT { get; set; }
        public string CODIGOTIPO { get; set; }
        public string TIPOPARTE { get; set; }
        public int EJERCICIO { get; set; }
        public string SERIE { get; set; }
        public int NUMERO { get; set; }
        public System.DateTime FECHAALTA { get; set; }
        public Nullable<System.DateTime> FECHAINTEGRACIONMOVILIDAD { get; set; }
        public Nullable<System.DateTime> FECHAINTEGRACIONORIGEN { get; set; }
        public Nullable<int> FORZARINTEGRACIONORIGEN { get; set; }
        public string ROWID { get; set; }
        public System.DateTime FECHAINSERCION { get; set; }
        public Nullable<System.DateTime> FECHAACTUALIZACION { get; set; }
        public int BORRADO { get; set; }
        public string CLIENTECODIGO { get; set; }
        public string CLIENTENOMBRE { get; set; }
        public string CLIENTEDIRECCION { get; set; }
        public string CLIENTEPOBLACION { get; set; }
        public Nullable<int> IDRESPONSABLE { get; set; }
        public System.DateTime FECHAINTERVENCION { get; set; }
        public string TIEMPO { get; set; }
        public string DESC_MANT { get; set; }
        public string DESC_SERV { get; set; }
        public Nullable<int> ADMINISTRADORCODIGO { get; set; }
        public string ADMINISTRADORNOMBRE { get; set; }
        public string ADMINISTRADORTELEFONO { get; set; }
        public string ADMINISTRADOREMAIL { get; set; }
        public string AFECTADONOMBRE { get; set; }
        public string AFECTADOTELEFONO { get; set; }
        public string PERSONANOMBRE { get; set; }
        public string PERSONATELEFONO { get; set; }
        public int IDTECNICO1 { get; set; }
        public Nullable<int> IDTECNICO2 { get; set; }
        public Nullable<int> IDTECNICO3 { get; set; }
        public Nullable<int> IDVEHICULO1 { get; set; }
        public Nullable<int> IDVEHICULO2 { get; set; }
        public Nullable<int> IDVEHICULO3 { get; set; }
        public Nullable<int> ITX_TERMINAL { get; set; }
        public Nullable<int> MARCADO { get; set; }
        public string CODIGOTIPOFASE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_CITA> GEN_CITA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_CONTACTO> GEN_CONTACTO { get; set; }
        public virtual GEN_EMPRESA GEN_EMPRESA { get; set; }
        public virtual GEN_ESTADO GEN_ESTADO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_EVENTO> GEN_EVENTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_FOTO> GEN_FOTO { get; set; }
        public virtual GEN_USUARIOS GEN_USUARIOS { get; set; }
        public virtual GEN_USUARIOS GEN_USUARIOS1 { get; set; }
        public virtual GEN_USUARIOS GEN_USUARIOS2 { get; set; }
        public virtual GEN_USUARIOS GEN_USUARIOS3 { get; set; }
        public virtual GEN_VEHICULO GEN_VEHICULO { get; set; }
        public virtual GEN_VEHICULO GEN_VEHICULO1 { get; set; }
        public virtual GEN_VEHICULO GEN_VEHICULO2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_OTCONFIRMADA> GEN_OTCONFIRMADA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_OTINCIDENCIA> GEN_OTINCIDENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_OTMATERIAL> GEN_OTMATERIAL { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_OTTAREA> GEN_OTTAREA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_OTUSUARIO> GEN_OTUSUARIO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_OTVEHICULO> GEN_OTVEHICULO { get; set; }
    }
}
