//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsurbideWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_CITA
    {
        public int ID { get; set; }
        public string ROWID { get; set; }
        public int USUARIOID { get; set; }
        public Nullable<int> OTID { get; set; }
        public int IDEMPRESA { get; set; }
        public string ID_INT { get; set; }
        public System.DateTime FECHAHORAINICIO { get; set; }
        public System.DateTime FECHAHORAFIN { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHAINSERCION { get; set; }
        public Nullable<System.DateTime> FECHAACTUALIZACION { get; set; }
        public int BORRADO { get; set; }
        public Nullable<int> ITX_TERMINAL { get; set; }
        public Nullable<int> MARCADO { get; set; }
        public string CODIGOTIPO { get; set; }
        public Nullable<int> EJERCICIO { get; set; }
        public string SERIE { get; set; }
        public Nullable<int> NUMERO { get; set; }
        public string CODIGOTIPOFASE { get; set; }
    
        public virtual GEN_EMPRESA GEN_EMPRESA { get; set; }
        public virtual GEN_OT GEN_OT { get; set; }
        public virtual GEN_USUARIOS GEN_USUARIOS { get; set; }
    }
}
