//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsurbideWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_OTCONFIRMADA
    {
        public int ID { get; set; }
        public int OTID { get; set; }
        public int JORNADAID { get; set; }
        public Nullable<int> TSGARANTIA { get; set; }
        public string TSGARANTIAOBSERV { get; set; }
        public string TRABAJOSREA { get; set; }
        public string NOMBREFIRMA { get; set; }
        public string DNIFIRMA { get; set; }
        public string FIRMACLIENTE { get; set; }
        public string FIRMATECNICO { get; set; }
        public string M_PRE_PERIODO { get; set; }
        public string M_PRE_OBSERVACIONES { get; set; }
        public Nullable<int> M_PRE_CONGARANTIA { get; set; }
        public Nullable<int> M_PRE_SINGARANTIA { get; set; }
        public Nullable<int> M_PRE_CONGARANTIA24 { get; set; }
        public Nullable<double> M_PRE_PRECIO { get; set; }
        public Nullable<double> M_PRE_TIEMPO { get; set; }
        public Nullable<int> M_PRE_OPERARIOS { get; set; }
        public string M_PRE_OBSERVACCESOS { get; set; }
        public string R_PRE_OBSERVACIONES { get; set; }
        public string R_PRE_OBSERVACCESOS { get; set; }
        public Nullable<double> R_PRE_PRECIO { get; set; }
        public Nullable<double> R_PRE_TIEMPO { get; set; }
        public Nullable<int> R_PRE_OPERARIOS { get; set; }
        public string ROWID { get; set; }
        public System.DateTime FECHAINSERCION { get; set; }
        public Nullable<System.DateTime> FECHAACTUALIZACION { get; set; }
        public int BORRADO { get; set; }
        public int PDF_GENERADO { get; set; }
        public Nullable<int> ITX_TERMINAL { get; set; }
        public Nullable<int> PDF_MANT { get; set; }
        public Nullable<int> PDF_REP { get; set; }
        public Nullable<int> PDF_INCIDENCIA { get; set; }
        public Nullable<int> PAGADO { get; set; }
    
        public virtual GEN_JORNADA GEN_JORNADA { get; set; }
        public virtual GEN_OT GEN_OT { get; set; }
    }
}
