//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsurbideWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_CONTACTO
    {
        public int ID { get; set; }
        public int OTID { get; set; }
        public int IDEMPRESA { get; set; }
        public string ID_INT { get; set; }
        public string CODIGOCLIENTE { get; set; }
        public string CITANOMBRE { get; set; }
        public string CITATELEFONO { get; set; }
        public string CITACARGO { get; set; }
        public Nullable<int> CITACONFIRMADO { get; set; }
        public string CITAOBSERVACIONES { get; set; }
        public string ROWID { get; set; }
        public System.DateTime FECHAINSERCION { get; set; }
        public Nullable<System.DateTime> FECHAACTUALIZACION { get; set; }
        public int BORRADO { get; set; }
        public Nullable<int> ITX_TERMINAL { get; set; }
        public Nullable<int> MARCADO { get; set; }
    
        public virtual GEN_EMPRESA GEN_EMPRESA { get; set; }
        public virtual GEN_OT GEN_OT { get; set; }
    }
}
