//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsurbideWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_EVENTO
    {
        public int ID { get; set; }
        public Nullable<int> OTID { get; set; }
        public int JORNADAID { get; set; }
        public int TIPOEVENTO { get; set; }
        public System.DateTime FECHAEVENTO { get; set; }
        public Nullable<double> LATITUD { get; set; }
        public Nullable<double> LONGITUD { get; set; }
        public string ROWID { get; set; }
        public System.DateTime FECHAINSERCION { get; set; }
        public Nullable<System.DateTime> FECHAACTUALIZACION { get; set; }
        public int BORRADO { get; set; }
        public Nullable<int> ITX_TERMINAL { get; set; }
    
        public virtual GEN_JORNADA GEN_JORNADA { get; set; }
        public virtual GEN_OT GEN_OT { get; set; }
    }
}
