//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsurbideWebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class GEN_JORNADA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GEN_JORNADA()
        {
            this.GEN_EVENTO = new HashSet<GEN_EVENTO>();
            this.GEN_OTCONFIRMADA = new HashSet<GEN_OTCONFIRMADA>();
        }
    
        public int ID { get; set; }
        public int USUARIOID { get; set; }
        public System.DateTime INICIO { get; set; }
        public Nullable<System.DateTime> FIN { get; set; }
        public string ROWID { get; set; }
        public System.DateTime FECHAINSERCION { get; set; }
        public Nullable<System.DateTime> FECHAACTUALIZACION { get; set; }
        public int BORRADO { get; set; }
        public Nullable<int> ITX_TERMINAL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_EVENTO> GEN_EVENTO { get; set; }
        public virtual GEN_USUARIOS GEN_USUARIOS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GEN_OTCONFIRMADA> GEN_OTCONFIRMADA { get; set; }
    }
}
