//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IsurbideWebAPI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class XOne_IsurbideEntities : DbContext
    {
        public XOne_IsurbideEntities()
            : base("name=XOne_IsurbideEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GEN_CITA> GEN_CITA { get; set; }
        public virtual DbSet<GEN_CLIENTE> GEN_CLIENTE { get; set; }
        public virtual DbSet<GEN_CONTACTO> GEN_CONTACTO { get; set; }
        public virtual DbSet<GEN_EMPRESA> GEN_EMPRESA { get; set; }
        public virtual DbSet<GEN_ESTADO> GEN_ESTADO { get; set; }
        public virtual DbSet<GEN_EVENTO> GEN_EVENTO { get; set; }
        public virtual DbSet<GEN_FAMILIA> GEN_FAMILIA { get; set; }
        public virtual DbSet<GEN_FOTO> GEN_FOTO { get; set; }
        public virtual DbSet<GEN_JORNADA> GEN_JORNADA { get; set; }
        public virtual DbSet<GEN_MATERIAL> GEN_MATERIAL { get; set; }
        public virtual DbSet<GEN_OT> GEN_OT { get; set; }
        public virtual DbSet<GEN_OTCONFIRMADA> GEN_OTCONFIRMADA { get; set; }
        public virtual DbSet<GEN_OTINCIDENCIA> GEN_OTINCIDENCIA { get; set; }
        public virtual DbSet<GEN_OTMATERIAL> GEN_OTMATERIAL { get; set; }
        public virtual DbSet<GEN_OTTAREA> GEN_OTTAREA { get; set; }
        public virtual DbSet<GEN_OTUSUARIO> GEN_OTUSUARIO { get; set; }
        public virtual DbSet<GEN_OTVEHICULO> GEN_OTVEHICULO { get; set; }
        public virtual DbSet<GEN_TAREA> GEN_TAREA { get; set; }
        public virtual DbSet<GEN_USUARIOS> GEN_USUARIOS { get; set; }
        public virtual DbSet<GEN_VEHICULO> GEN_VEHICULO { get; set; }
        public virtual DbSet<GEN_VERSIONES> GEN_VERSIONES { get; set; }
    }
}
